# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
                ('code', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='project_code',
        ),
        migrations.AddField(
            model_name='project',
            name='project_actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_actual_pgm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_actual_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(default='TBA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_enddate',
            field=models.DateField(default='2099-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_location',
            field=models.CharField(default='tba', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_startdate',
            field=models.DateField(default='2099-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_week_number',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Network'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectType'),
            preserve_default=False,
        ),
    ]
