# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20171023_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectStatus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectType'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_week_number',
            field=models.SmallIntegerField(editable=False),
        ),
    ]
