# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ismaterial', models.BooleanField()),
                ('islabour', models.BooleanField()),
            ],
        ),
    ]
