# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdate', models.DateField()),
                ('hours', models.PositiveSmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Project')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Timesheet')),
            ],
        ),
        migrations.CreateModel(
            name='WeekendDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekenddate', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workcode', models.PositiveSmallIntegerField()),
                ('workcode_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='timesheetdetail',
            name='workcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Workcode'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='weekenddate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.WeekendDate'),
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together=set([('employee', 'weekenddate')]),
        ),
    ]
