# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_workcode_workcode_serial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheetdetail',
            unique_together=set([('timesheet', 'workcode', 'project', 'workdate', 'hours')]),
        ),
    ]
