# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_auto_20171020_2333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheetdetail',
            unique_together=set([('timesheet', 'workcode', 'project', 'workdate')]),
        ),
    ]
