# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_auto_20171020_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekenddate',
            name='current_weekenddate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
